# Generated by Django 4.2.2 on 2023-11-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('text1', models.CharField(max_length=100)),
                ('image', models.ImageField(default='uploads/images/sliders.jpg', upload_to='uploads/sliders')),
            ],
        ),
    ]
