# Generated by Django 4.2.2 on 2023-11-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_sliders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliders',
            name='image',
            field=models.ImageField(default='uploads/sliders/profile.jpg', upload_to='uploads/sliders'),
        ),
    ]
